/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo_evalfinal_jchm;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOSE
 */
public class FormVentanaPrincipal extends javax.swing.JFrame {

    // ---variables globales para usarlas en otros formularios ----
    Calendar calend = new GregorianCalendar();
    Integer idEmpleado = FormIniciarSesion.idEmpleado;
    String TotalPago;
    String dni;
    String NumCP;
    String ItemCmbDcto;
    double sumPago = 0.0;
    
    // Obtenemos el idEmpleado en base al nombre de usuario
    
    
    public FormVentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Menu Principal");
        //System.out.println(idEmpleado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmNuevoUser = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoU = new javax.swing.JTextField();
        txtNombreU = new javax.swing.JTextField();
        txtPasswordU = new javax.swing.JTextField();
        btnRegistrarNuevoUsuario = new javax.swing.JButton();
        btnSalirU = new javax.swing.JButton();
        frmNuevoCliente = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtDNIC = new javax.swing.JTextField();
        txtNombreC = new javax.swing.JTextField();
        txtApellidoC = new javax.swing.JTextField();
        txtDireccionC = new javax.swing.JTextField();
        btnRegistrarNuevoCliente = new javax.swing.JButton();
        btnSalirC = new javax.swing.JButton();
        frmReportarVenta = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblResultadoReporte = new javax.swing.JTable();
        btnSalirReport = new javax.swing.JButton();
        btnReportar = new javax.swing.JButton();
        cmbTipoReporte = new javax.swing.JComboBox<>();
        frmVenta = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtCodVendRV = new javax.swing.JTextField();
        txtNomVendRV = new javax.swing.JTextField();
        txtClienteRV = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtDcto = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblProductoEncontrado = new javax.swing.JTable();
        btnBuscarProducto = new javax.swing.JButton();
        btnCalcDcto = new javax.swing.JButton();
        btnEfectuar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbTipoRV = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        datechFechaVenta = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtmailVendRV = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        cmbTituloRV = new javax.swing.JComboBox();
        txtTotalRV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbEdicionRV = new javax.swing.JComboBox();
        frmNuevaPublicacion = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtAutorP = new javax.swing.JTextField();
        btnRegPubli = new javax.swing.JButton();
        btnSalirP1 = new javax.swing.JButton();
        cmbTipoP = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        lblCodigoTipo = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtTituloP = new javax.swing.JTextField();
        txtPrecioP = new javax.swing.JTextField();
        txtStockP = new javax.swing.JTextField();
        txtEdicionP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        BmArchivo = new javax.swing.JMenu();
        opSalir = new javax.swing.JMenuItem();
        bmGestionar = new javax.swing.JMenu();
        opNuevaPublicacion = new javax.swing.JMenuItem();
        bmTransaccion = new javax.swing.JMenu();
        opRegistVenta = new javax.swing.JMenuItem();
        opReportVenta = new javax.swing.JMenuItem();

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Ingresar Datos de Usuario");

        jLabel3.setText("Codigo");

        jLabel4.setText("Nombre");

        jLabel5.setText("Password");

        txtCodigoU.setBackground(new java.awt.Color(255, 255, 204));

        btnRegistrarNuevoUsuario.setText("Registrar");

        btnSalirU.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreU)
                                    .addComponent(txtPasswordU, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRegistrarNuevoUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(btnSalirU))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPasswordU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarNuevoUsuario)
                    .addComponent(btnSalirU))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frmNuevoUserLayout = new javax.swing.GroupLayout(frmNuevoUser.getContentPane());
        frmNuevoUser.getContentPane().setLayout(frmNuevoUserLayout);
        frmNuevoUserLayout.setHorizontalGroup(
            frmNuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        frmNuevoUserLayout.setVerticalGroup(
            frmNuevoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setText("Ingresar Datos de Cliente");

        jLabel24.setText("DNI");

        jLabel25.setText("Nombre");

        jLabel26.setText("Apellido");

        jLabel27.setText("Direccion");

        btnRegistrarNuevoCliente.setText("Registrar");

        btnSalirC.setText("Salir");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel23)
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreC)
                                    .addComponent(txtApellidoC)
                                    .addComponent(txtDireccionC, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnRegistrarNuevoCliente)
                .addGap(26, 26, 26)
                .addComponent(btnSalirC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtDNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtApellidoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtDireccionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirC)
                    .addComponent(btnRegistrarNuevoCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frmNuevoClienteLayout = new javax.swing.GroupLayout(frmNuevoCliente.getContentPane());
        frmNuevoCliente.getContentPane().setLayout(frmNuevoClienteLayout);
        frmNuevoClienteLayout.setHorizontalGroup(
            frmNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmNuevoClienteLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        frmNuevoClienteLayout.setVerticalGroup(
            frmNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setText("Reportar Venta");

        jLabel29.setText("Seleccione tipo de Publicacion");

        tblResultadoReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tblResultadoReporte);

        btnSalirReport.setText("Salir");
        btnSalirReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirReportActionPerformed(evt);
            }
        });

        btnReportar.setText("Reportar");
        btnReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportarActionPerformed(evt);
            }
        });

        cmbTipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel28))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(33, 33, 33)
                                .addComponent(cmbTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReportar)
                                .addGap(48, 48, 48))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnSalirReport)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel28)
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReportar)
                        .addComponent(jLabel29)
                        .addComponent(cmbTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(btnSalirReport)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frmReportarVentaLayout = new javax.swing.GroupLayout(frmReportarVenta.getContentPane());
        frmReportarVenta.getContentPane().setLayout(frmReportarVentaLayout);
        frmReportarVentaLayout.setHorizontalGroup(
            frmReportarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frmReportarVentaLayout.setVerticalGroup(
            frmReportarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel30.setText("Registrar Venta");

        jLabel31.setText("Codigo:");

        jLabel32.setText("Nombre y Apellido:");

        jLabel33.setText("Fecha:");

        jLabel34.setText("Ingrese Nombres y Apellidos del Cliente:");

        jLabel35.setText("Elija Tipo de Producto:");

        jLabel36.setText("Cantidad");

        jLabel37.setText("TOTAL VENTA (S/.)");

        jLabel38.setText("Descuento:");

        txtCodVendRV.setEnabled(false);

        txtNomVendRV.setEnabled(false);

        txtDcto.setEnabled(false);

        tblProductoEncontrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tblProductoEncontrado);

        btnBuscarProducto.setText("Buscar Publicacion");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        btnCalcDcto.setText("Calcular Dcto");
        btnCalcDcto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcDctoActionPerformed(evt);
            }
        });

        btnEfectuar.setText("Efectuar Venta");
        btnEfectuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectuarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cmbTipoRV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoRVActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setText("Datos del Producto a Vender");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel48.setText("Datos del Vendedor");

        jLabel6.setText("Correo:");

        txtmailVendRV.setEnabled(false);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel49.setText("Datos del Cliente");

        jLabel50.setText("Elija titulo a Vender:");

        cmbTituloRV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTituloRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTituloRVActionPerformed(evt);
            }
        });

        jLabel7.setText("Edicion:");

        cmbEdicionRV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel30)
                .addGap(126, 126, 126)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datechFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtClienteRV, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodVendRV))
                                    .addComponent(jLabel48))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNomVendRV, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtmailVendRV))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator4))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoRV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTituloRV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEdicionRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(btnEfectuar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDcto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalRV, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(btnCalcDcto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel33))
                                .addGap(7, 7, 7))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(datechFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtCodVendRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(txtNomVendRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtmailVendRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtClienteRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel39)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cmbTipoRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50)
                    .addComponent(cmbTituloRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cmbEdicionRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcDcto)
                    .addComponent(jLabel37)
                    .addComponent(txtDcto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(txtTotalRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEfectuar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frmVentaLayout = new javax.swing.GroupLayout(frmVenta.getContentPane());
        frmVenta.getContentPane().setLayout(frmVentaLayout);
        frmVentaLayout.setHorizontalGroup(
            frmVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        frmVentaLayout.setVerticalGroup(
            frmVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel9.setBackground(new java.awt.Color(153, 255, 255));
        jPanel9.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel40.setText("Ingresar Datos de Publicación");

        jLabel41.setText("Codigo generado:");

        jLabel42.setText("Titulo:");

        jLabel43.setText("Autor:");

        jLabel44.setText("Edición:");

        btnRegPubli.setText("Registrar");
        btnRegPubli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegPubliActionPerformed(evt);
            }
        });

        btnSalirP1.setText("Salir");
        btnSalirP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirP1ActionPerformed(evt);
            }
        });

        cmbTipoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoPActionPerformed(evt);
            }
        });

        jLabel45.setText("Tipo");

        lblCodigoTipo.setText("CODIGO DE ITEM");

        jLabel46.setText("Precio:");

        jLabel47.setText("Stock:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel40))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCodigoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(txtAutorP)
                            .addComponent(txtTituloP)
                            .addComponent(cmbTipoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(btnRegPubli)
                                .addGap(76, 76, 76)
                                .addComponent(btnSalirP1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtStockP, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(txtPrecioP)
                            .addComponent(txtEdicionP))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel40)
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(lblCodigoTipo))
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtTituloP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txtAutorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtEdicionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(txtPrecioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(txtStockP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegPubli)
                    .addComponent(btnSalirP1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frmNuevaPublicacionLayout = new javax.swing.GroupLayout(frmNuevaPublicacion.getContentPane());
        frmNuevaPublicacion.getContentPane().setLayout(frmNuevaPublicacionLayout);
        frmNuevaPublicacionLayout.setHorizontalGroup(
            frmNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frmNuevaPublicacionLayout.setVerticalGroup(
            frmNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 440, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_evalfinal_jchm/BookStore_ventas.png"))); // NOI18N

        BmArchivo.setText("Archivo");

        opSalir.setText("Salir");
        opSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSalirActionPerformed(evt);
            }
        });
        BmArchivo.add(opSalir);

        jMenuBar1.add(BmArchivo);

        bmGestionar.setText("Gestionar");

        opNuevaPublicacion.setText("Nueva Publicacion");
        opNuevaPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opNuevaPublicacionActionPerformed(evt);
            }
        });
        bmGestionar.add(opNuevaPublicacion);

        jMenuBar1.add(bmGestionar);

        bmTransaccion.setText("Transaccion");

        opRegistVenta.setText("Registrar Venta");
        opRegistVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opRegistVentaActionPerformed(evt);
            }
        });
        bmTransaccion.add(opRegistVenta);

        opReportVenta.setText("Reportar Montos Venta");
        opReportVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opReportVentaActionPerformed(evt);
            }
        });
        bmTransaccion.add(opReportVenta);

        jMenuBar1.add(bmTransaccion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opSalirActionPerformed

    private void opNuevaPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opNuevaPublicacionActionPerformed
        this.frmNuevaPublicacion.setVisible(true);
        this.frmNuevaPublicacion.setSize(600,500);
        this.frmNuevaPublicacion.setLocationRelativeTo(null);
        this.txtTituloP.setText("");
        this.txtAutorP.setText("");
        this.txtEdicionP.setText("");
        this.txtPrecioP.setText("");
        this.txtStockP.setText("");
        
        cConnection con = new cConnection();
        
        String query = "select * from tipo";
               
        cmbTipoP.removeAllItems();   // Cargamos el combo con la lista de tipos disponibles
        
        try {
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()) {
                cmbTipoP.addItem(rs.getString("descripcion"));
            }
        }
        catch(SQLException e) {
            
        }
        
    }//GEN-LAST:event_opNuevaPublicacionActionPerformed

    private void btnSalirP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirP1ActionPerformed
        frmNuevaPublicacion.setVisible(false);
    }//GEN-LAST:event_btnSalirP1ActionPerformed

    private void cmbTipoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoPActionPerformed
        Integer cont = 0;
        String idTipo = "";
        String codTipo;  // Variable para almacenar el codigo que se generará 
        
        cConnection con = new cConnection();
        
        String query = "select * from tipo where descripcion = '" + this.cmbTipoP.getSelectedItem() + "'";
        
        try {
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            if(rs.next()) {
                cont = rs.getInt("contador");
                idTipo = rs.getString("idTipo");
            }
            
            codTipo = idTipo + String.format("%05d", cont+1);   // generacion del codigo de la publicacion
            
            this.lblCodigoTipo.setText(codTipo);
            
        }
        catch(SQLException e) {
            
        }
    }//GEN-LAST:event_cmbTipoPActionPerformed

    private void btnRegPubliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegPubliActionPerformed
        
        String idPublicacion = this.lblCodigoTipo.getText();
        String titulo = this.txtTituloP.getText();
        String idTipo = idPublicacion.substring(0, 3);
        String autor = this.txtAutorP.getText();
        Integer nroEdicion = Integer.parseInt(this.txtEdicionP.getText());
        Float precio = Float.parseFloat(this.txtPrecioP.getText());
        Integer stock = Integer.parseInt(this.txtStockP.getText());
        
        cConnection con = new cConnection();
        
        String query = "INSERT INTO publicacion(idPublicacion,titulo,idTipo,autor,nroEdicion,precio,stock) values('"
                + idPublicacion + "', '"
                + titulo + "', '"
                + idTipo + "', '"
                + autor + "', "
                + nroEdicion + ", "
                + precio + ", "
                + stock + ")";
        
        query += "\nupdate tipo set contador = (select contador+1 from tipo where idTipo = '"
                + idTipo + "') where idTipo = '" + idTipo + "'";
        
        try {
            Statement st = null;
            st = con.ObtenerConexion().createStatement();
            st.executeUpdate(query);
                    
            JOptionPane.showMessageDialog(null, "Se guardó nueva publicación con éxito...");
            this.txtTituloP.setText("");
            this.txtAutorP.setText("");
            this.txtEdicionP.setText("");
            this.txtPrecioP.setText("");
            this.txtStockP.setText("");
            this.cmbTipoP.setSelectedIndex(0);
            
        }
        catch(SQLException e) {
            System.out.println(e);
        }
        
        try {
            con.closeConnection();
        }
        catch(Exception e) {
            
        }
    }//GEN-LAST:event_btnRegPubliActionPerformed

    private void opRegistVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opRegistVentaActionPerformed
        this.frmVenta.setVisible(true);
        this.frmVenta.setLocationRelativeTo(null);
        this.frmVenta.setSize(878, 640);
        
        /**borrar***/
        idEmpleado = 71458;
        
        
        cConnection con = new cConnection();
        
        String query = "select idEmpleado, nombre + ' ' + apellido as nomAp, email from empleado where idEmpleado = " + idEmpleado.toString() ;
        //System.out.println(query);
        try {
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            if(rs.next()) {
                this.txtCodVendRV.setText(idEmpleado.toString());
                this.txtNomVendRV.setText(rs.getString("nomAp"));
                this.txtmailVendRV.setText(rs.getString("email"));
            }
            
        }
        catch(SQLException e) {
            System.out.println(e);
        }
        
        /**** llenamos los combos *****/
        
        //combo de tipos
        this.cmbTipoRV.removeAllItems();
        query = "select * from tipo";
        
        try {
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()) {
                this.cmbTipoRV.addItem(rs.getString("descripcion"));
            }
            
        }
        catch(SQLException sqle) {
            System.out.println(sqle);
        }
        
        ///combo de titulos
        this.cmbTituloRV.removeAllItems();
        query = "select * from publicacion where idTipo = (select idTipo from tipo where descripcion = '" + this.cmbTipoRV.getSelectedItem() + "')";
        
        try {
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()) {
                this.cmbTituloRV.addItem(rs.getString("titulo"));
            }
            
        }
        catch(SQLException sqle) {
            System.out.println(sqle);
        }
        
        
        //Combo de ediciones
        this.cmbEdicionRV.removeAllItems();
        query = "select * from publicacion where titulo = '" + this.cmbTituloRV.getSelectedItem() + "'";
        
        try {
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()) {
                this.cmbEdicionRV.addItem(rs.getString("nroEdicion"));
            }
            
        }
        catch(SQLException sqle) {
            System.out.println(sqle);
        }
        
        /**** llenamos los combos *****/
        
        try {
            con.closeConnection();
        }
        catch(Exception e) {
            System.out.println(e);
        }
        
        DefaultTableModel dtRegistroVenta = new DefaultTableModel();
        this.tblProductoEncontrado.setModel(dtRegistroVenta);
        
        dtRegistroVenta.addColumn("ID Publicacion");
        dtRegistroVenta.addColumn("Titulo");
        dtRegistroVenta.addColumn("Autor");
        dtRegistroVenta.addColumn("Edicion");
        dtRegistroVenta.addColumn("Precio");
        dtRegistroVenta.addColumn("Stock");
        
    }//GEN-LAST:event_opRegistVentaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        frmVenta.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbTipoRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoRVActionPerformed
        
        cConnection con = new cConnection();
              
        
        ///combo de titulos
        this.cmbTituloRV.removeAllItems();
        String query = "select * from publicacion where idTipo = (select idTipo from tipo where descripcion = '" + this.cmbTipoRV.getSelectedItem() + "')";
        
        try {
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()) {
                this.cmbTituloRV.addItem(rs.getString("titulo"));
            }
            
        }
        catch(SQLException sqle) {
            System.out.println(sqle);
        }
        
         //Combo de ediciones
        this.cmbEdicionRV.removeAllItems();
        query = "select * from publicacion where titulo = '" + this.cmbTituloRV.getSelectedItem() + "'";
        
        try {
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()) {
                this.cmbEdicionRV.addItem(rs.getString("nroEdicion"));
            }
            
        }
        catch(SQLException sqle) {
            System.out.println(sqle);
        }
        
        try {
            con.closeConnection();
        }
        catch(Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_cmbTipoRVActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        cConnection con = new cConnection();
        
        String titu = this.cmbTituloRV.getSelectedItem().toString();
        String edic = this.cmbEdicionRV.getSelectedItem().toString();
        
        String query = "select * from publicacion where titulo = '" + titu + "' and nroEdicion = " + edic;
        
        try {
            
            DefaultTableModel dtRegistroVenta = new DefaultTableModel();
            this.tblProductoEncontrado.setModel(dtRegistroVenta);

            dtRegistroVenta.addColumn("ID Publicacion");
            dtRegistroVenta.addColumn("Titulo");
            dtRegistroVenta.addColumn("Autor");
            dtRegistroVenta.addColumn("Edicion");
            dtRegistroVenta.addColumn("Precio");
            dtRegistroVenta.addColumn("Stock");
            
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()) {
                dtRegistroVenta.addRow(new Object[] {rs.getString("idPublicacion"),rs.getString("titulo"),rs.getString("autor"),rs.getInt("nroedicion"),rs.getFloat("precio"),rs.getInt("stock") });
            }
        }
        catch(Exception e) {
            
        }
        
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void cmbTituloRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTituloRVActionPerformed
        cConnection con = new cConnection();
        
        //Combo de ediciones
        this.cmbEdicionRV.removeAllItems();
        String query = "select * from publicacion where titulo = '" + this.cmbTituloRV.getSelectedItem() + "'";
        
        try {
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()) {
                this.cmbEdicionRV.addItem(rs.getString("nroEdicion"));
            }
            
        }
        catch(SQLException sqle) {
            System.out.println(sqle);
        }
        
        try {
            con.closeConnection();
        }
        catch(Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_cmbTituloRVActionPerformed

    private void btnCalcDctoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcDctoActionPerformed
        cConnection con = new cConnection();
        Float dcto;
        Integer cant = Integer.parseInt(this.txtCantidad.getText());
        Float precio = Float.parseFloat(this.tblProductoEncontrado.getValueAt(0, 4).toString());
        Float precio_total;
        
        String query = "select * from promocion where " + this.txtCantidad.getText() + " between cantMin and cantMax";
        System.out.println(query);
        try {
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            if(rs.next()) {
                this.txtDcto.setText(String.valueOf(rs.getFloat("porcentaje")));
                precio_total = precio * cant * (1 - Float.parseFloat(this.txtDcto.getText()));
                this.txtTotalRV.setText(String.valueOf(precio_total));
            }
        }
        catch(Exception e) {
            
        }
    }//GEN-LAST:event_btnCalcDctoActionPerformed

    private void btnEfectuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectuarActionPerformed
        cConnection con = new cConnection();
        
        String idVenta = "";
        String cliente;
        String fecha;
        String idEmpleado1;
        String idPublicacion;
        String cant;
        String precio;
        String dcto;
        String subtotal;
        String impuesto;
        String total;
        
        String query = "select max(idVenta)+1 as idVentaNext from venta";
        
        try {
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            if(rs.next()) {
                idVenta = String.valueOf(rs.getInt("idVentaNext"));
            }
        }
        catch(Exception e) {
        }
        
        cliente = this.txtClienteRV.getText();
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        fecha = sdf.format(this.datechFechaVenta.getDate());
        
        idEmpleado1 = this.txtCodVendRV.getText();
        idPublicacion = this.tblProductoEncontrado.getValueAt(0, 0).toString();
        cant = this.txtCantidad.getText();
        precio = this.tblProductoEncontrado.getValueAt(0, 4).toString();
        
        subtotal = String.valueOf(Integer.parseInt(cant) * Float.parseFloat(precio));
        
        dcto = this.txtDcto.getText();
        impuesto = "0";
        total = this.txtTotalRV.getText();
        
        query = "INSERT INTO venta values("
                + idVenta + ", '"
                + cliente + "', '"
                + fecha + "', "
                + idEmpleado1 + ", '"
                + idPublicacion + "', "
                + cant + ", "
                + precio + ", "
                + dcto + ", "
                + subtotal + ", "
                + impuesto + ", "
                + total + ")";
        System.out.println(query);
        
        
            JOptionPane.showMessageDialog(null, "Venta Guardada");
        try {
            Statement st = null;
            st = con.ObtenerConexion().createStatement();
            st.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null, "Venta Guardada");
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEfectuarActionPerformed

    private void opReportVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opReportVentaActionPerformed
        
        cConnection con = new cConnection();
        this.frmReportarVenta.setVisible(true);
        this.frmReportarVenta.setLocationRelativeTo(null);
        this.frmReportarVenta.setSize(878, 640);
        
        //combo de tipos
        this.cmbTipoReporte.removeAllItems();
        String query = "select * from tipo";
        
        try {
            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()) {
                this.cmbTipoReporte.addItem(rs.getString("descripcion"));
            }
            
        }
        catch(SQLException sqle) {
            System.out.println(sqle);
        }
        
        DefaultTableModel dtRegistroReporte = new DefaultTableModel();
        this.tblResultadoReporte.setModel(dtRegistroReporte);
        
        dtRegistroReporte.addColumn("Cliente");
        dtRegistroReporte.addColumn("Fecha");
        dtRegistroReporte.addColumn("Titulo");
        dtRegistroReporte.addColumn("Cantidad");
        dtRegistroReporte.addColumn("Total");
        
        
    }//GEN-LAST:event_opReportVentaActionPerformed

    private void btnSalirReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirReportActionPerformed
        this.frmReportarVenta.setVisible(false);
    }//GEN-LAST:event_btnSalirReportActionPerformed

    private void btnReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportarActionPerformed
        cConnection con = new cConnection();
        
        String cliente;
        String fecha;
        String Titulo;
        String Cantidad;
        String Total;
        
        String query = "select v.cliente, v.fecha,p.titulo, v.cantidad,v.total from venta as v left join publicacion as p on p.idPublicacion = v.idPublicacion";
        
        try {
            DefaultTableModel dtRegistroReporte = new DefaultTableModel();
            this.tblResultadoReporte.setModel(dtRegistroReporte);

            dtRegistroReporte.addColumn("Cliente");
            dtRegistroReporte.addColumn("Fecha");
            dtRegistroReporte.addColumn("Titulo");
            dtRegistroReporte.addColumn("Cantidad");
            dtRegistroReporte.addColumn("Total");

            Statement st = con.ObtenerConexion().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()) {
                dtRegistroReporte.addRow(new Object[] {rs.getString("cliente"),rs.getString("fecha"),rs.getString("titulo"),String.valueOf(rs.getInt("cantidad")),String.valueOf(rs.getFloat("total"))} );
            }
        }
        catch(Exception e){
            
        }
        
    }//GEN-LAST:event_btnReportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BmArchivo;
    private javax.swing.JMenu bmGestionar;
    private javax.swing.JMenu bmTransaccion;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnCalcDcto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEfectuar;
    private javax.swing.JButton btnRegPubli;
    private javax.swing.JButton btnRegistrarNuevoCliente;
    private javax.swing.JButton btnRegistrarNuevoUsuario;
    private javax.swing.JButton btnReportar;
    private javax.swing.JButton btnSalirC;
    private javax.swing.JButton btnSalirP1;
    private javax.swing.JButton btnSalirReport;
    private javax.swing.JButton btnSalirU;
    private javax.swing.JComboBox cmbEdicionRV;
    public javax.swing.JComboBox<String> cmbTipoP;
    public javax.swing.JComboBox cmbTipoRV;
    private javax.swing.JComboBox<String> cmbTipoReporte;
    public javax.swing.JComboBox cmbTituloRV;
    private com.toedter.calendar.JDateChooser datechFechaVenta;
    private javax.swing.JFrame frmNuevaPublicacion;
    private javax.swing.JFrame frmNuevoCliente;
    private javax.swing.JFrame frmNuevoUser;
    private javax.swing.JFrame frmReportarVenta;
    private javax.swing.JFrame frmVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblCodigoTipo;
    private javax.swing.JMenuItem opNuevaPublicacion;
    private javax.swing.JMenuItem opRegistVenta;
    private javax.swing.JMenuItem opReportVenta;
    private javax.swing.JMenuItem opSalir;
    private javax.swing.JTable tblProductoEncontrado;
    private javax.swing.JTable tblResultadoReporte;
    private javax.swing.JTextField txtApellidoC;
    private javax.swing.JTextField txtAutorP;
    private javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtClienteRV;
    public javax.swing.JTextField txtCodVendRV;
    private javax.swing.JTextField txtCodigoU;
    public javax.swing.JTextField txtDNIC;
    public javax.swing.JTextField txtDcto;
    private javax.swing.JTextField txtDireccionC;
    private javax.swing.JTextField txtEdicionP;
    public javax.swing.JTextField txtNomVendRV;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtNombreU;
    private javax.swing.JTextField txtPasswordU;
    private javax.swing.JTextField txtPrecioP;
    private javax.swing.JTextField txtStockP;
    private javax.swing.JTextField txtTituloP;
    public javax.swing.JTextField txtTotalRV;
    private javax.swing.JTextField txtmailVendRV;
    // End of variables declaration//GEN-END:variables
}
